.TH OCIOCONVERT 1
.SH NAME
ocioconvert \- apply colorspace transform to an image
.SH SYNOPSIS
.B ocioconvert
.RI [ options ] " output-file" ...
.SH DESCRIPTION
This manual page documents briefly the
.B ocioconvert
command.
.SH OPTIONS
A summary of options is included below.
.TP
.TP
.BI "\-\-float\-attribute " N=F
name=float pair defining OCIO float atribute
.TP
.BI "\-\-int\-attribute " N=I
name=int pair defining OCIO int atribute
.TP
.BI "\-\-string\-attribute " N=S
name=string pair defining OCIO string atribute
.SH SEE ALSO
.BR ociobakelut (1),
.BR ociocheck (1),
.BR ociolutimage (1).
.br
.B /usr/share/doc/opencolorio/OpenColorIO.pdf
