.TH OCIODISPLAY "1" "August 2023" "ociodisplay " "User Commands"
.SH NAME
ociodisplay \- apply a colorspace conversion to an image sequence
.SH DESCRIPTION
.SS "Keys:"
.TP
Ctrl+Up:
Exposure +1/4 stop (in scene linear)
.IP
Ctrl+Down: Exposure \fB\-1\fR/4 stop (in scene linear)
Ctrl+Home: Reset Exposure + Gamma
.TP
Alt+Up:
Gamma up (post display transform)
.TP
Alt+Down:
Gamma down (post display transform)
.TP
Alt+Home:
Reset Exposure + Gamma
.TP
C:
View Color
.TP
R:
View Red
.TP
G:
View Green
.TP
B:
View Blue
.TP
A:
View Alpha
.TP
L:
View Luma
.TP
Right\-Mouse Button:
Configure Display / Transform / ColorSpace / Looks / Optimization
.IP
Esc: Quit
